#ifndef _CONFIG_H_
#define _CONFIG_H_

#include "types.h" // TIndex / TPort

#define ENABLE_VHOST

const TIndex WIFI_MAX_DECONNECTED_CLIENT = 15;

const bool LOST_PACKET_BY_DEFAULT=false;

const TPort DEFAULT_WIFI_CLIENT_PORT_VHOST = 8211;
const TPort DEFAULT_WIFI_CLIENT_PORT_INET = DEFAULT_WIFI_CLIENT_PORT_VHOST+1;

const TPort DEFAULT_WIFI_SPY_PORT = DEFAULT_WIFI_CLIENT_PORT_VHOST+2;

const TPort DEFAULT_CTRL_PORT = DEFAULT_WIFI_CLIENT_PORT_VHOST+3;

#define DEFAULT_ADDRESS_IP "127.0.0.1"

#ifdef _DEBUG
	// #define _VERBOSE1
	// #define _VERBOSE2
#endif

#endif
