name: Build
on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v7
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake make g++ pkg-config
          sudo apt-get install -y libnl-3-dev libnl-genl-3-dev
      - name: Build
        run: |
          mkdir build
          cd build
          cmake ..
          make
      - name: Upload
        uses: actions/upload-artifact@v5
        with:
          path: build/vwifi-*
